/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.itu.MapOfDenmark;

import dk.itu.MapOfDenmark.View.TitleUI;
import javafx.application.Application;
import javafx.stage.Stage;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;

import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Node;

public class App extends Application {
    public static String path;
    String string;


    @Override
    public void start(Stage primaryStage) throws Exception {
        new Controller(new TitleUI(primaryStage));
    }

    public static void main(String[] args) {
        launch(args);
    }
}
